### ISSUE TITLE
Met Office forecast data

### ISSUE THREAD

**Issue by niallrobinson** [CubeBrowser/cube-explorer#1]
Hi everyone - there is a THREDDS server with OpenDAP available here
http://thredds.3dvis.informaticslab.co.uk/thredds/catalog.html

It non-operational, so we can't guarantee it'll be up for every, but it gives you something to start playing with.

EDIT: that doesn't work so we can use NOAAs for the time being
http://www.esrl.noaa.gov/psd/thredds/catalog/Datasets/catalog.html

for instance http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep/

**Comment by kjbovis** [comment]
This looks pretty useful, I like the metadata in the catalogue. Does it require a lot of effort to maintain it?

**Comment by niallrobinson** [comment]
I don't maintain it, so I can't say for sure, but I don't think so. It will just tick away (although the data will update to the latest forecasts, which can persist some of it if that helps). We can potentially try adding other people's data to the THREDDS/OpenDAP, but the guys who are responsible for it didn't seem overjoyed at the prospect. At the very least, we can put people's data into an Amazon s3 bucket so people can download the files (as opposed to OpenDAPing them)

**Comment by kjbovis** [comment]
Speaking with Ag Stephens he said that the catalogue is compiled by examining meta-data in NetCDF files. Very clever.

**Comment by niallrobinson** [comment]
That sounds right. We can definitely give it a go when people have data available. Iris does a very nice job of just letting you hit the OpenDAP sever directly i.e. you can lazily download just the data you need

**Comment by marqh** [comment]
Hi @niallrobinson 

I feel like i'm missing a crucial piece of information, as I am unable to load a dataset from this service

I browsed to
http://thredds.3dvis.informaticslab.co.uk/thredds/catalog/testLab/catalog.html
then
http://thredds.3dvis.informaticslab.co.uk/thredds/catalog/testLab/catalog.html?dataset=labDatasetScan/umqvaa_cloud_volume_fraction_in_atmosphere_layer_20160209T0000Z_pc036.nc

This has an opendap link listed.  However, if i run

```
import iris
c = iris.load('http://thredds.3dvis.informaticslab.co.uk/thredds/dodsC/testLab/umqvaa_cloud_volume_fraction_in_atmosphere_layer_20160209T0000Z_pc036.nc.html')
```

i get

```
...
self._dataset = netCDF4.Dataset(self._filename, mode='r')
  File "netCDF4.pyx", line 1464, in netCDF4.Dataset.__init__ (netCDF4.c:22181)

```

I thought that this should just work, such as:
http://scitools.org.uk/iris/docs/latest/whatsnew/1.4.html?highlight=opendap#load-opendap

@niallrobinson please could you post a runnable example of loading a dataset from these sources for us

thank you
mark

**Comment by niallrobinson** [comment]
your right - doesn't work. We can use NOAAs for the time being?
http://www.esrl.noaa.gov/psd/thredds/catalog/Datasets/catalog.html
