### ISSUE TITLE
Clearer way to access to iris Cube on HoloCube

### ISSUE THREAD

**Issue by philippjfr** [CubeBrowser/cube-explorer#19]
In a recent meeting we discussed that accessing the cube data on one of our HoloCube wrappers should be very clear. By default the types in HoloViews allow accessing the underlying data using the `.data` attribute. The suggestion we made was that the `HoloCube` object should have a `.cube` attribute/property, which is an alias for `.data`.

**Comment by marqh** [comment]
closed based on discussions within the team
