### ISSUE TITLE
Defining plotting normalization behavior for large datasets

### ISSUE THREAD

**Issue by philippjfr** [CubeBrowser/cube-explorer#20]
~~Currently when plotting in holoviews the plotting code will attempt to figure out the normalization ranges for each frame before anything is plotted. This is true even when the normalization options are set not to compute ranges across all frames. This is fine for datasets which can be held in memory but for lazily loaded data (like a large Iris Cube) this can cause considerable issues. I've opened a matching issue in holoviews (https://github.com/ioam/holoviews/issues/561) but I also wanted to keep track of this issue here.~~

**Comment by philippjfr** [comment]
Turns out I already implemented what I outlined above a while ago but there's still some issues about normalization to settle. Note that when I'm talking about normalization here all I really mean is whether HoloViews will try to compute the range along the dimensions in the plot for each frame and whether to compute it across multiple axes in a single plot. These ranges are used to inform extent calculations for the plots and are also used as the color range of an image.

Currently we provide control over these with framewise and axiswise, which specify whether to compute the ranges across all frames and whether to compute it across multiple plots in a Layout respectively. Computing the ranges for all the frames, which could potentially be huge and located remotely, is definitely a bad idea.

So we'll still have to find a way to ensure that the framewise normalization option is enabled for large datasets by default (some threshold number of frames maybe?). We should also make it very clear that enabling it will start loading each chunk of data from the cube source to compute its range even if that's a terrabyte on some remote datasource. Note that this may still be useful for medium sized datasets, because each individual chunk (corresponding to a displayable Element) would be loaded into memory sequentially allowing you to normalize across several gigabytes on disk in a reasonable timeframe.

**Comment by marqh** [comment]
I think our backup position could be that plotting normalisation is per visualisation

This is not the ideal primary option but it is safe

however, on consultation with @pelson, we wonder if a more useful solution might be a 'guess normalization' default, which takes the first slice, applies some "let's give it 10% at each end" and gives a stable normalization

The usage pattern of normalization being stable whilst sliding through dimensions is pretty valuable.  Perhaps we should try and keep this, even if it's based on guesswork unless we're provided with useful defaults by a lookup

**Comment by marqh** [comment]
I like the option we have discussed which enables users to specify data ranges and normalisation, this is something many users will expect.

If we can additionally provide some sensible defaults for known 
(standard_name, units)
pairs, such that a number of phenomena provide a useful set of defaults, that would be great

I would like to investigate how we could provide a small set of such defaults in a way which is easy for people to suggest extensions to

**Comment by marqh** [comment]
this seems closely linked to choice of colour palette, which are also triggered by particular standard names (in my view)

is this a separate (linked) issue?
have we captured it somewhere?

**Comment by marqh** [comment]
closed by #58
