### ISSUE TITLE
Split CubeExplorer Prototype notebook into distinct Tutorials

### ISSUE THREAD

**Issue by philippjfr** [CubeBrowser/cube-explorer#21]
The current CubeExplorer prototype notebook includes a collection of different examples to demonstrate the capabilities of the current holocube interface. As we move forward we should move sections on projections, features/tiles and most importantly the Cube interface itself into separate Tutorials and then expand on each some more.

**Comment by jbednar** [comment]
And I guess the tutorials would then move into a doc/Tutorials directory, to form the basis for a web site demonstrating how to use this package?

**Comment by philippjfr** [comment]
Yes, ideally we'd move towards that, even if we don't put up the website right away.

**Comment by marqh** [comment]
superceded by #55
