### ISSUE TITLE
Seasonal ensemble

### ISSUE THREAD

**Issue by marqh** [CubeBrowser/cube-explorer#3]
This Iris gallery includes this example
http://scitools.org.uk/iris/docs/latest/examples/Meteorology/lagged_ensemble.html
using data from
https://github.com/SciTools/iris-sample-data
https://github.com/SciTools/iris-sample-data/tree/master/sample_data/GloSea4

If we simplify the load process from this example, using the same data:

```
import numpy as np
import iris
import iris.coords
import iris.plot as iplt

def realization_metadata(cube, field, fname):
    if not cube.coords('realization'):
        realization_number = fname[-6:-3]
        realization_coord = iris.coords.AuxCoord(np.int32(realization_number), 'realization')
        cube.add_aux_coord(realization_coord)


surface_temp = iris.load_cube(iris.sample_data_path('GloSea4', 'ensemble_???.pp'),
              iris.Constraint('surface_temperature', realization=lambda value: True),
              callback=realization_metadata)
print surface_temp
```

we get a 4 dimensional cube of surface temperature data:

```
surface_temperature / (K)           (realization: 13; time: 6; latitude: 145; longitude: 192)
     Dimension coordinates:
          realization                           x         -            -               -
          time                                  -         x            -               -
          latitude                              -         -            x               -
          longitude                             -         -            -               x
     Auxiliary coordinates:
          forecast_period                       x         x            -               -
          forecast_reference_time               x         x            -               -
     Attributes:
          STASH: m01s00i024
          source: Data from Met Office Unified Model
          um_version: 7.6
     Cell methods:
          mean: time (1 hour)

```

A scientific programmer needs to apply this load process, within a notebook session, then explore the realization dimension and the time dimension, looking at 2D filled contour plots over latitude and longitude.

**Comment by marqh** [comment]
@philippjfr
@jlstevens
@jbednar
@rrenfrow86

**Comment by marqh** [comment]
I would like to use this issue to drive:
#2

**Comment by jlstevens** [comment]
Great! 

This looks like a good example to start with. Complicated enough to get us going without involving too many elements that could distract us from the big picture.

**Comment by marqh** [comment]
the plot command makes a cartopy geoaxes, which has a coastlines method

```
 cf = iplt.contourf(cube, contour_levels)

  # add coastlines
  plt.gca().coastlines()
```

**Comment by jbednar** [comment]
Implemented; see example /share/notebooks/CubeExplorer_Prototype.ipynb  at
http://metoffice.continuum.io:8000/
