### ISSUE TITLE
Need to host notebooks in JupyterHub

### ISSUE THREAD

**Issue by arulalant** [CubeBrowser/cube-explorer#4]
We need to host the [JupyterHub](https://github.com/jupyter/jupyterhub) as server instead of just Jupyter alone. You can read the detailed [documentation](https://jupyterhub.readthedocs.org/en/latest/) of it. JupyterHub, a multi-user server, manages and proxies multiple instances of the single-user  Jupyter notebook server. So that we can configure LDAP based authentication to execute the notebooks.

Though JupyterHub requires Python 3.0 to run, still we can select which python version kernel need to be executed when we create new notebook or executing existing notebook!

Hope the following links help us to deploy both JupyterHub and Python2.7 kernel: 
      1. https://linuxcluster.wordpress.com/2015/08/13/basic-setup-and-configuration-of-jupyterhub-with-python-3-4-3/
      2. https://linuxcluster.wordpress.com/2015/08/16/using-python-2-on-jupyterhub/
      3. http://stackoverflow.com/questions/29118729/how-to-install-multiple-ipython-3-0-kernels-python-2-7-python-3-4-etc-wit
      4. https://github.com/jupyter/jupyter/issues/71

Thanks from NCMRWF

**Comment by marqh** [comment]
Hi @arulalant 

I expect that all cube browser capabilities will be able to run inside a standalone notebook instance and as part of a JupyterHub instance

I think there are some interesting angles which JupyterHub might bring, for sharing output, so I think it is worth considering investigating setting up a temporary instance for this project.

I think this additive to the project; we don't want to be bound to JupyterHub, but we should be compatible with it, I think.

@jbednar @philippjfr @jlstevens does this concur with you views?

**Comment by jlstevens** [comment]
Yes, absolutely!

We would want to leverage JupyterHub only to make multi-user notebook sharing easier and not to get tied up with it in any way. Anything we would make available on JupyterHub would be runnable on a local machine using a regular, standalone notebook server.

**Comment by rrenfrow86** [comment]
@jlstevens - are we calling this issue completed or de we want to work out the access list first?

**Comment by jlstevens** [comment]
I am happy to have this issue closed as long as it is clear that we are operating a whitelist and anyone who would like access needs to send me their github user name.

You can access JupyterHub here: http://metoffice.continuum.io:8000/

I suggest we use this issue as a place for people to request access whether or not it is now closed.

**Comment by arulalant** [comment]
@jlstevens  Thanks. could you please give me access. My github user name is "arulalant" 
I am getting the following error when I am trying to start the server.
"Failed to start your server. Please contact admin."

Let me close this issue.

**Comment by jlstevens** [comment]
@arulalant It should be working for you now as I've added your account.

**Comment by arulalant** [comment]
@jlstevens Thanks.  http://metoffice.continuum.io:8000/ is pretty awesome, especially the last one (In [17]) visualizing the ensembles Versus time slicers.

Just bringing to your notice that I couldn't make copy of the notebook due to permission denied.

**Comment by jlstevens** [comment]
> Just bringing to your notice that I couldn't make copy of the notebook due to permission denied.

You can't edit a copy of the notebook? After running File -> Make a Copy?

If so, I'll have to look into it again as this is part of the recommended workflow. I'm fairly sure it was working when I last tested it!

**Comment by philippjfr** [comment]
I assume it's to do with the permissions in the share/notebooks folder.

**Comment by jlstevens** [comment]
@philippjfr That is probably true. The thing is the symbolic link is to the git repository and if I change the permissions there, that will almost certainly count as a change that git will want to track.

I suppose I can try to commit and push the permissions change and hope it sticks (as it should!) as the repository is updated over time.

**Comment by jlstevens** [comment]
@arulalant I've updated the permissions and tested it again. Making a copy should work now!

**Comment by arulalant** [comment]
@jlstevens Thanks, now I able to make copy of notebook and work on that. So we can focus on creating notebooks and run it in JupyterHub.
