### ISSUE TITLE
Review Design Issues

### ISSUE THREAD

**Issue by marqh** [CubeBrowser/cube-explorer#53]
- [x] Guess Bounds
- [x] Analysis Methods (#18)
- [x] Time Formatting
- [x] Slicing
- [x] Vector Field
- [x] holocube - project and element names

**Comment by jlstevens** [comment]
We didn't look at it explicitly while we were brainstorming, but also have a [wiki page that is useful to explain these issues in more detail](https://github.com/CubeBrowser/cube-explorer/wiki/Open-Design-Decisions).

I think everything mentioned on the wiki falls into the list above but it is worth looking at for some additional context.

**Comment by marqh** [comment]
#63 for guess bounds

**Comment by marqh** [comment]
#64 and #12 for methods and slicing

**Comment by marqh** [comment]
vector field : #66
