### ISSUE TITLE
Colour and Range

### ISSUE THREAD

**Issue by marqh** [CubeBrowser/cube-explorer#58]
Provide an implementation of specifying colour map choice and range based on cube name and units of measure

building on 
#20 #34 #35

**Comment by marqh** [comment]
find colormap in iris

**Comment by jlstevens** [comment]
To start, consider these dimensions: `air_temperature`, `air_pressure` , `specific_humidity`

`colormaps = {'air_temperature':('coolwarm', [('K', (253,323)), ('C', (-30,40))]),
                        'air_pressure': ('brewer_Blues_09', [('Pa', (5e4, 2e5))] ) }
`

Syntax:

```
gv.dim.air_temperature.K
```

**Comment by jlstevens** [comment]
I've passed the new preset system over to @marqh and the necessary code is now in cube_browser and HoloViews. Are we ready to close this issue?

**Comment by philippjfr** [comment]
Has it actually been merged? https://github.com/ioam/holoviews/pull/644 is still open.

**Comment by jlstevens** [comment]
Sorry yes, let's see if we can get that PR merged now.

**Comment by jlstevens** [comment]
ioam/holoviews#644 has been merged now so the preset system should now work fine using HoloViews master.
